env:
  - RUST_SKIA_TAG="0.33.0"
if: tag IS present
os:
  - osx
  - linux
dist: bionic
language: node_js
node_js:
  - lts/*
  - node
cache:
  - cargo
  - npm
before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export RUSTUP_OPTIONS="--default-host x86_64-pc-windows-msvc --default-toolchain stable-x86_64-pc-windows-msvc"; fi
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env" || true
  - rustc --version
  - cargo --version
  # Install NPM packages
  - node -v
  - npm -v
  # Clone the rust-skia repo with the proper tag
  - git clone --depth 1 --branch $RUST_SKIA_TAG https://github.com/rust-skia/rust-skia.git ../rust-skia
  - npm install -g neon-cli
  # Build rust-skia from source on linux (use downloaded binaries on mac)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sed -i.bak 's/^skia-safe.*/skia-safe = { path = "..\/..\/rust-skia\/skia-safe", features = ["textlayout"] }/' native/Cargo.toml; fi
  - travis_wait 25 npm run build
script:
  - npm test
  - npm run package
  - npm run upload-binary
