os:
  - osx
  - linux
  - windows
dist: focal
language: node_js
node_js:
  - lts/*
  - node
cache:
  - cargo
  - npm
before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export RUSTUP_OPTIONS="--default-host x86_64-pc-windows-msvc --default-toolchain stable-x86_64-pc-windows-msvc"; fi
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env" || true
  - rustc --version
  - cargo --version
  # Install NPM packages
  - node -v
  - npm -v
  - npm install
script:
  - npm run package
  - npm test
#   - if [ -n "$TRAVIS_TAG" ]; then npm run upload-binary || exit 0; fi
deploy:
  draft: true
  provider: releases
  api_key: "$API_KEY"
  file_glob: true
  file: build/stage/${TRAVIS_TAG}/*
  on:
    repo: samizdatco/skia-canvas
    tags: true
  skip_cleanup: true