os:
  - osx
  - linux
language: node_js
node_js:
  - lts/*
  - node
cache:
  - cargo
  - npm
before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env"
  - rustc --version
  - cargo --version
  # Install NPM packages
  - node -v
  - npm -v
  - npm install
script:
  - npm test
  - npm run package
  - if [ -n "$TRAVIS_TAG" ]; then npm run upload-binary || exit 0; fi
