os:
  - osx
  - linux
language: node_js
node_js:
  - lts/*
  - node
cache:
  - cargo
  - npm
before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env"
  - rustc --version
  - cargo --version
  # Install NPM packages
  - node -v
  - npm -v
  - npm install
script:
  - npm test
  - rm -rf native/target
  - rm -rf native/artifacts.json
  - npm run package
  # Publish when using '[publish binary]' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then npm run upload-binary || exit 0; fi;
