env:
  - RUST_SKIA_TAG="0.33.0"
os:
  - osx
  - linux
dist: bionic
language: node_js
node_js:
  - lts/*
  - node
cache:
  - cargo
  - npm
before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export RUSTUP_OPTIONS="--default-host x86_64-pc-windows-msvc --default-toolchain stable-x86_64-pc-windows-msvc"; fi
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env" || true
  - rustc --version
  - cargo --version
  # Install NPM packages
  - node -v
  - npm -v
  - npm install -g neon-cli
  # Clone the rust-skia repo with the proper tag
  - git clone --depth 1 --branch $RUST_SKIA_TAG https://github.com/rust-skia/rust-skia.git ../rust-skia
  - sed -i 's/^skia-safe.*/skia-safe = { path = "..\/..\/rust-skia\/skia-safe", features = ["textlayout"] }/' native/Cargo.toml
# if: tag IS present
script:
  - npm install
  - npm test
  - npm run package
  - if [ -n "$TRAVIS_TAG" ]; then npm run upload-binary || exit 0; fi
